#+TITLE: Eddie is Eddie's (Emacs) directory developed in Emacs

* Introduction
By default Emacs kinda sucks. Most people customize the hell out of
Emacs. This is Eddie, my personal configuration of Emacs. Emacs is
customized by loading a directory containing Emacs Lisp code. That
directory is =~/.emacs.d= and it contains a an /initialization/ file
called =init.el=; the file where all the magic begins.

# Already I'm wanting an Emacs mode for interacting with the OS X
# system dictionary that I've been dreaming about for /years/.
# TODO: build said Emacs mode

This is an experiment in whimsical yet practical literate programming,
extreme customization, and extreme organization. Hopefully it will
evolve past experimental.

** History
I started using Emacs when I got my hands on my first Linux book. The
book was called /Linux Administration: A Beginner's Guide/ and it came
with a Red Hat Linux CD. I got the book used from an alternative
bookstore in Sacramento, CA. I had a friend that worked there that
gave me a crazy discount. The CD saved my from having to download
Linux on my dial-up connection and the book saved me from needing an
internet connection when I learned my win-modem wouldn't work when
running Linux.

This was an important event in my life because the book had a
paragraph or so on text editors. It said that an effective Linux
administrator should use either Emacs or Vi. I picked Emacs because it
was first in the list and it probably was first because someone
decided to list the two editors alphabetically.

However, to blatantly copy a line from /Bill & Ted's Excellent
Adventure/, dedicate yourself to the "proposition which was true in my
time, just as it's true today," pick either Emacs or Vi—there are no
other choices. If your craft involves editing text, anything else is a
mistake.

* How This Works
This directory contains my Emacs configuration and
customization. Think of it like the preferences or settings for other
applications, but it is in fact much more. It is also extensions,
plugins, and even the documentation.

When Emacs is launched it tries to load a Lisp file called the
/initialization file/, in the case the file is
=~/.emacs.d/init.el=. That file contains just enough Lisp to bootstrap
my configuration. It does this by reading /this file/ (=README.org=)
and processing it using Org-babel. This file is both the effective
entry point for my configuration and its documentation.

** The Initialization File
The =init.el= file contains the following Lisp code that bootstraps my
configuration. Unfortunately, GitHub doesn't honor org-mode includes.

#+INCLUDE: "init.el" src emacs-lisp

* Configurations
My configuration is organized into several files loaded bellow. This
is the only code that /this file/ contains that gets executed by
Org-babel. It is the /actual/ code thanks to the power of literate
programming.

#+BEGIN_SRC emacs-lisp
(message "Loading Eddie's configuration…")
(eddie/load-file "eddie-core")
#+END_SRC
