(add-hook 'org-mode-hook (lambda () (auto-fill-mode)))
;; disable stupid outline style indentation
(setq org-adapt-indentation nil)
(setq org-src-preserve-indentation nil)
(setq org-edit-src-content-indentation 0)

;; Org babel
;; (require 'ob-sh)
;; (require 'ob-ditaa)
;; (require 'ob-js)
;; (require 'ob-python)
;; (require 'ob-C)
;; (require 'ob-shell)
;; (require 'ob-sql)
(org-babel-do-load-languages
 'org-babel-load-languages
 '((emacs-lisp . t)
   (shell . t)
   (C . t)
;;   (cpp . t)
   (css . t)
   (ditaa . t)
   (gnuplot . t)
   (haskell . t)
   (java . t)
   (js . t)
   (latex . t)
   (lisp . t)
   (makefile . t)
   (org . t)
   (perl . t)
   (python . t)
   (R . t)
   (ruby . t)
   ;; (scala . t)
   (scheme . t)
   (sed . t)
   (sql . t)
   (sqlite . t)))
(setq org-confirm-babel-evaluate nil)
